name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 6
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm build
      - uses: actions/upload-artifact@v4
        with:
          name: railsim-lollipop-onl
          path: dist/
