name: Build App
on:
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '10'
      - run: npm ci
      - run: npm build
      - uses: actions/upload-artifact@v3
        with:
          name: railsim-lollipop-onl
          path: dist/